name: Job
permissions: write-all
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: clone source
        run: |
          curl -H "Authorization: Bearer olp_7sJHiPA056Tj43mxcKgyQRAXMHg9Q31VcKjc" "https://www.overleaf.com/api/v1/projects/68660e3e227e10e0977b1216/download/zip  -o source.zip
          ls -R
          unzip ./source.zip -d ./四川省高考数学导数大题汇总


      # - name: commit
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
      #     git add .
      #     git commit -m 'update'
      #     git push